import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from '@/modules/sidebar';
import AddBlocks from '@/modules/pages/blocks/AddBlocks';
import Header from '@/modules/header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen bg-white">
          {/* Sidebar */}
          <Sidebar />
          <main className="flex-1 flex flex-col">
            <Header />
            {children}
            <AddBlocks />
          </main>
        </div>
      </body>
    </html>
  );
}
